import { Pokemon } from '../models/pokemon.model';

export const POKEMON_DATA: Pokemon[] = [
  {
    id: 1,
    name: 'Bulbasaur',
    type: ['Grass', 'Poison'],
    height: 7,
    weight: 69,
    description: 'A small quadruped Pokémon that can survive for days on sunlight alone.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
    hp: 45,
    attack: 49,
    defense: 49,
    spAtk: 65,
    spDef: 65,
    speed: 45
  },
  {
    id: 2,
    name: 'Ivysaur',
    type: ['Grass', 'Poison'],
    height: 10,
    weight: 130,
    description: 'When the bulb on its back grows large, it appears to support the Pokémon\'s weight.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png',
    hp: 60,
    attack: 62,
    defense: 63,
    spAtk: 80,
    spDef: 80,
    speed: 60
  },
  {
    id: 3,
    name: 'Venusaur',
    type: ['Grass', 'Poison'],
    height: 20,
    weight: 1000,
    description: 'The flower on its back catches the sun\'s rays and converts them into energy.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    hp: 80,
    attack: 82,
    defense: 83,
    spAtk: 100,
    spDef: 100,
    speed: 80
  },
  {
    id: 4,
    name: 'Charmander',
    type: ['Fire'],
    height: 6,
    weight: 85,
    description: 'The flame on its tail shows the strength of its life force.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
    hp: 39,
    attack: 52,
    defense: 43,
    spAtk: 60,
    spDef: 50,
    speed: 65
  },
  {
    id: 5,
    name: 'Charmeleon',
    type: ['Fire'],
    height: 11,
    weight: 190,
    description: 'It attacks by spitting balls of fire. It is quite aggressive.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png',
    hp: 58,
    attack: 64,
    defense: 58,
    spAtk: 80,
    spDef: 65,
    speed: 80
  },
  {
    id: 6,
    name: 'Charizard',
    type: ['Fire', 'Flying'],
    height: 17,
    weight: 905,
    description: 'It flies around the sky in search of prey. Its fire never extinguishes.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
    hp: 78,
    attack: 84,
    defense: 78,
    spAtk: 109,
    spDef: 85,
    speed: 100
  },
  {
    id: 7,
    name: 'Squirtle',
    type: ['Water'],
    height: 5,
    weight: 90,
    description: 'Often found in small ponds and lakes. Prefers damp places.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
    hp: 44,
    attack: 48,
    defense: 65,
    spAtk: 50,
    spDef: 64,
    speed: 43
  },
  {
    id: 8,
    name: 'Wartortle',
    type: ['Water'],
    height: 10,
    weight: 225,
    description: 'It hides in water to stalk unsuspecting prey.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png',
    hp: 59,
    attack: 63,
    defense: 80,
    spAtk: 65,
    spDef: 80,
    speed: 58
  },
  {
    id: 9,
    name: 'Blastoise',
    type: ['Water'],
    height: 16,
    weight: 855,
    description: 'The cannons on its shell fire water at high power.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
    hp: 79,
    attack: 83,
    defense: 100,
    spAtk: 85,
    spDef: 105,
    speed: 78
  },
  {
    id: 10,
    name: 'Caterpie',
    type: ['Bug'],
    height: 3,
    weight: 29,
    description: 'Its body is filled with a foul-smelling venom.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png',
    hp: 45,
    attack: 52,
    defense: 43,
    spAtk: 60,
    spDef: 55,
    speed: 35
  },
  {
    id: 11,
    name: 'Metapod',
    type: ['Bug'],
    height: 7,
    weight: 99,
    description: 'This Pokémon is vulnerable to attack while its shell is soft.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png',
    hp: 50,
    attack: 20,
    defense: 55,
    spAtk: 25,
    spDef: 25,
    speed: 30
  },
  {
    id: 12,
    name: 'Butterfree',
    type: ['Bug', 'Flying'],
    height: 11,
    weight: 320,
    description: 'In battle, it flaps its wings at high speed to release highly toxic powder.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png',
    hp: 60,
    attack: 45,
    defense: 50,
    spAtk: 80,
    spDef: 80,
    speed: 70
  },
  {
    id: 13,
    name: 'Weedle',
    type: ['Bug', 'Poison'],
    height: 3,
    weight: 32,
    description: 'Often found in forests, eating leaves.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png',
    hp: 40,
    attack: 35,
    defense: 30,
    spAtk: 20,
    spDef: 20,
    speed: 50
  },
  {
    id: 14,
    name: 'Kakuna',
    type: ['Bug', 'Poison'],
    height: 6,
    weight: 100,
    description: 'Almost incapable of moving, this Pokémon can only harden its shell to protect itself.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png',
    hp: 45,
    attack: 25,
    defense: 50,
    spAtk: 25,
    spDef: 25,
    speed: 35
  },
  {
    id: 15,
    name: 'Beedrill',
    type: ['Bug', 'Poison'],
    height: 10,
    weight: 295,
    description: 'Extremely territorial, this Pokémon will chase after anything that wanders into its nest.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png',
    hp: 65,
    attack: 80,
    defense: 40,
    spAtk: 45,
    spDef: 80,
    speed: 75
  },
  {
    id: 16,
    name: 'Pidgeot',
    type: ['Normal', 'Flying'],
    height: 15,
    weight: 395,
    description: 'This Pokémon is fully covered by thick, fluffy feathers.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png',
    hp: 40,
    attack: 60,
    defense: 30,
    spAtk: 31,
    spDef: 31,
    speed: 56
  },
  {
    id: 17,
    name: 'Pidgeotto',
    type: ['Normal', 'Flying'],
    height: 11,
    weight: 300,
    description: 'Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png',
    hp: 63,
    attack: 60,
    defense: 55,
    spAtk: 50,
    spDef: 50,
    speed: 71
  },
  {
    id: 18,
    name: 'Pidgeot',
    type: ['Normal', 'Flying'],
    height: 15,
    weight: 395,
    description: 'When hunting, it skims the surface of water at high speed to pick off unwary prey.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png',
    hp: 83,
    attack: 100,
    defense: 75,
    spAtk: 70,
    spDef: 70,
    speed: 91
  },
  {
    id: 19,
    name: 'Rattata',
    type: ['Normal'],
    height: 3,
    weight: 35,
    description: 'Bites anything when it moves. Very stable in the wild.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png',
    hp: 30,
    attack: 56,
    defense: 35,
    spAtk: 25,
    spDef: 35,
    speed: 72
  },
  {
    id: 20,
    name: 'Raticate',
    type: ['Normal'],
    height: 7,
    weight: 185,
    description: 'It uses its sharp claws to dig through the ground and hide in the shadows.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png',
    hp: 55,
    attack: 81,
    defense: 60,
    spAtk: 50,
    spDef: 70,
    speed: 97
  },
  {
    id: 21,
    name: 'Spearow',
    type: ['Normal', 'Flying'],
    height: 3,
    weight: 20,
    description: 'Eats small bugs in grassy areas and plains.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png',
    hp: 40,
    attack: 60,
    defense: 30,
    spAtk: 31,
    spDef: 31,
    speed: 70
  },
  {
    id: 22,
    name: 'Fearow',
    type: ['Normal', 'Flying'],
    height: 12,
    weight: 380,
    description: 'With its huge, sturdy wings, it can keep aloft without ever having to land on the ground.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png',
    hp: 65,
    attack: 90,
    defense: 65,
    spAtk: 61,
    spDef: 61,
    speed: 100
  },
  {
    id: 23,
    name: 'Ekans',
    type: ['Poison'],
    height: 20,
    weight: 69,
    description: 'Moves silently and stealthily. Eats the eggs of birds, it is said.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png',
    hp: 35,
    attack: 60,
    defense: 44,
    spAtk: 40,
    spDef: 54,
    speed: 55
  },
  {
    id: 24,
    name: 'Arbok',
    type: ['Poison'],
    height: 35,
    weight: 650,
    description: 'The pattern on its belly appears to be a frightening face.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png',
    hp: 60,
    attack: 85,
    defense: 69,
    spAtk: 65,
    spDef: 79,
    speed: 80
  },
  {
    id: 25,
    name: 'Pikachu',
    type: ['Electric'],
    height: 4,
    weight: 60,
    description: 'When several of these Pokémon gather, their electricity can build and cause lightning storms.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
    hp: 35,
    attack: 55,
    defense: 40,
    spAtk: 50,
    spDef: 50,
    speed: 90
  },
  {
    id: 26,
    name: 'Raichu',
    type: ['Electric'],
    height: 8,
    weight: 300,
    description: 'When it is angered, it immediately discharges the energy stored in the pouches in its cheeks.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png',
    hp: 60,
    attack: 90,
    defense: 55,
    spAtk: 90,
    spDef: 80,
    speed: 110
  },
  {
    id: 27,
    name: 'Sandshrew',
    type: ['Ground'],
    height: 6,
    weight: 120,
    description: 'Burrows deep underground in arid locations far from water.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png',
    hp: 50,
    attack: 75,
    defense: 85,
    spAtk: 20,
    spDef: 30,
    speed: 40
  },
  {
    id: 28,
    name: 'Sandslash',
    type: ['Ground'],
    height: 10,
    weight: 295,
    description: 'Burrows underground to escape the heat.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png',
    hp: 75,
    attack: 100,
    defense: 110,
    spAtk: 45,
    spDef: 55,
    speed: 65
  },
  {
    id: 29,
    name: 'Nidoran♀',
    type: ['Poison'],
    height: 4,
    weight: 70,
    description: 'Females are more competitive with their beauty, and males are more crazed with greed and power.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png',
    hp: 55,
    attack: 47,
    defense: 52,
    spAtk: 40,
    spDef: 40,
    speed: 41
  },
  {
    id: 30,
    name: 'Nidorina',
    type: ['Poison'],
    height: 8,
    weight: 200,
    description: 'The female\'s horn develops slowly. Prefers physical attacks such as clawing and biting.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png',
    hp: 70,
    attack: 62,
    defense: 67,
    spAtk: 55,
    spDef: 55,
    speed: 56
  },
  {
    id: 31,
    name: 'Nidoqueen',
    type: ['Poison', 'Ground'],
    height: 13,
    weight: 600,
    description: 'The female\'s horn develops slowly. Prefers physical attacks such as clawing and biting.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png',
    hp: 90,
    attack: 92,
    defense: 87,
    spAtk: 75,
    spDef: 85,
    speed: 76
  },
  {
    id: 32,
    name: 'Nidoran♂',
    type: ['Poison'],
    height: 5,
    weight: 90,
    description: 'Females are more competitive with their beauty, and males are more crazed with greed and power.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png',
    hp: 46,
    attack: 57,
    defense: 40,
    spAtk: 40,
    spDef: 40,
    speed: 50
  },
  {
    id: 33,
    name: 'Nidorino',
    type: ['Poison'],
    height: 9,
    weight: 195,
    description: 'An aggressive Pokémon, it is well-suited to physical attacks.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png',
    hp: 61,
    attack: 72,
    defense: 57,
    spAtk: 55,
    spDef: 55,
    speed: 65
  },
  {
    id: 34,
    name: 'Nidoking',
    type: ['Poison', 'Ground'],
    height: 14,
    weight: 620,
    description: 'An aggressive Pokémon, it is well-suited to physical attacks.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png',
    hp: 81,
    attack: 102,
    defense: 77,
    spAtk: 75,
    spDef: 85,
    speed: 85
  },
  {
    id: 35,
    name: 'Clefairy',
    type: ['Fairy'],
    height: 6,
    weight: 75,
    description: 'A timid fairy Pokémon that is rarely seen.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png',
    hp: 35,
    attack: 48,
    defense: 48,
    spAtk: 35,
    spDef: 48,
    speed: 35
  },
  {
    id: 36,
    name: 'Clefable',
    type: ['Fairy'],
    height: 13,
    weight: 400,
    description: 'A timid fairy Pokémon that is rarely seen.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png',
    hp: 70,
    attack: 73,
    defense: 60,
    spAtk: 60,
    spDef: 73,
    speed: 60
  },
  {
    id: 37,
    name: 'Vulpix',
    type: ['Fire'],
    height: 6,
    weight: 99,
    description: 'It is said to emerge from volcanoes. At the time of birth, it has just one tail.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png',
    hp: 38,
    attack: 41,
    defense: 40,
    spAtk: 50,
    spDef: 65,
    speed: 65
  },
  {
    id: 38,
    name: 'Ninetales',
    type: ['Fire'],
    height: 11,
    weight: 199,
    description: 'It is said to emerge from volcanoes. It has lived for a thousand years.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png',
    hp: 73,
    attack: 76,
    defense: 75,
    spAtk: 81,
    spDef: 100,
    speed: 100
  },
  {
    id: 39,
    name: 'Jigglypuff',
    type: ['Normal', 'Fairy'],
    height: 5,
    weight: 55,
    description: 'When its huge eyes waver, it sings an enchanting song that lulls the enemy to sleep.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png',
    hp: 115,
    attack: 40,
    defense: 20,
    spAtk: 45,
    spDef: 25,
    speed: 20
  },
  {
    id: 40,
    name: 'Wigglytuff',
    type: ['Normal', 'Fairy'],
    height: 10,
    weight: 120,
    description: 'It bounces around happily like a rubber ball.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png',
    hp: 140,
    attack: 70,
    defense: 45,
    spAtk: 75,
    spDef: 50,
    speed: 45
  },
  {
    id: 41,
    name: 'Zubat',
    type: ['Poison', 'Flying'],
    height: 8,
    weight: 75,
    description: 'Emits ultrasonic cries while it moves. It is said to emerge from darkness even in the light.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png',
    hp: 40,
    attack: 45,
    defense: 35,
    spAtk: 30,
    spDef: 40,
    speed: 55
  },
  {
    id: 42,
    name: 'Golbat',
    type: ['Poison', 'Flying'],
    height: 16,
    weight: 550,
    description: 'Once it strikes, it relentlessly sinks its sharp fangs into its prey.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png',
    hp: 75,
    attack: 80,
    defense: 75,
    spAtk: 70,
    spDef: 75,
    speed: 90
  },
  {
    id: 43,
    name: 'Oddish',
    type: ['Grass', 'Poison'],
    height: 5,
    weight: 54,
    description: 'It uses the nutrients in the dark underground to generate energy.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png',
    hp: 45,
    attack: 50,
    defense: 55,
    spAtk: 75,
    spDef: 65,
    speed: 30
  },
  {
    id: 44,
    name: 'Gloom',
    type: ['Grass', 'Poison'],
    height: 8,
    weight: 86,
    description: 'It blooms with a very unpleasant odor in order to attract Pokémon.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png',
    hp: 60,
    attack: 65,
    defense: 70,
    spAtk: 85,
    spDef: 75,
    speed: 40
  },
  {
    id: 45,
    name: 'Vileplume',
    type: ['Grass', 'Poison'],
    height: 12,
    weight: 186,
    description: 'It is said that it spreads a pollen that smells like honey.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png',
    hp: 75,
    attack: 80,
    defense: 85,
    spAtk: 110,
    spDef: 90,
    speed: 50
  },
  {
    id: 46,
    name: 'Paras',
    type: ['Bug', 'Grass'],
    height: 3,
    weight: 35,
    description: 'Burrows to suck the blood of tree roots. The mushrooms on its back are not attached to the Pokémon.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png',
    hp: 35,
    attack: 70,
    defense: 55,
    spAtk: 55,
    spDef: 55,
    speed: 25
  },
  {
    id: 47,
    name: 'Parasect',
    type: ['Bug', 'Grass'],
    height: 10,
    weight: 295,
    description: 'The mushroom on its back is said to be a transformed parasite.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png',
    hp: 60,
    attack: 95,
    defense: 80,
    spAtk: 60,
    spDef: 80,
    speed: 30
  },
  {
    id: 48,
    name: 'Venonat',
    type: ['Bug', 'Poison'],
    height: 10,
    weight: 300,
    description: 'Lives in the shadows of tall trees where it eats insects.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png',
    hp: 60,
    attack: 55,
    defense: 50,
    spAtk: 40,
    spDef: 55,
    speed: 45
  },
  {
    id: 49,
    name: 'Venomoth',
    type: ['Bug', 'Poison'],
    height: 15,
    weight: 125,
    description: 'Moves silently through grass. It releases a cloud of highly toxic spores.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png',
    hp: 70,
    attack: 65,
    defense: 60,
    spAtk: 90,
    spDef: 75,
    speed: 90
  },
  {
    id: 50,
    name: 'Diglett',
    type: ['Ground'],
    height: 2,
    weight: 8,
    description: 'Lives about one yard underground where it feeds on plant roots and insects.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png',
    hp: 10,
    attack: 55,
    defense: 25,
    spAtk: 35,
    spDef: 45,
    speed: 95
  },
  {
    id: 51,
    name: 'Dugtrio',
    type: ['Ground'],
    height: 7,
    weight: 333,
    description: 'A team of Diglett triplets that can burrow to a depth of over 30 feet.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png',
    hp: 35,
    attack: 80,
    defense: 50,
    spAtk: 50,
    spDef: 70,
    speed: 120
  },
  {
    id: 52,
    name: 'Meowth',
    type: ['Normal'],
    height: 4,
    weight: 42,
    description: 'Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png',
    hp: 40,
    attack: 45,
    defense: 35,
    spAtk: 40,
    spDef: 40,
    speed: 90
  },
  {
    id: 53,
    name: 'Persian',
    type: ['Normal'],
    height: 10,
    weight: 320,
    description: 'Although its body is compact, it is skilled at sending out quick jabs.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png',
    hp: 65,
    attack: 70,
    defense: 60,
    spAtk: 65,
    spDef: 65,
    speed: 115
  },
  {
    id: 54,
    name: 'Psyduck',
    type: ['Water'],
    height: 8,
    weight: 196,
    description: 'It is always tormented by headaches. It uses psychic powers, but it is not a Psychic-type Pokémon.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png',
    hp: 50,
    attack: 52,
    defense: 48,
    spAtk: 65,
    spDef: 50,
    speed: 55
  },
  {
    id: 55,
    name: 'Golduck',
    type: ['Water'],
    height: 17,
    weight: 766,
    description: 'It is said to emerge from rivers to steal the shells of aquatic Pokémon.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png',
    hp: 80,
    attack: 82,
    defense: 78,
    spAtk: 95,
    spDef: 80,
    speed: 85
  },
  {
    id: 56,
    name: 'Mankey',
    type: ['Fighting'],
    height: 5,
    weight: 280,
    description: 'Extremely quick to anger. It could be docile one moment then thrashing away the next.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png',
    hp: 40,
    attack: 80,
    defense: 35,
    spAtk: 35,
    spDef: 45,
    speed: 70
  },
  {
    id: 57,
    name: 'Primeape',
    type: ['Fighting'],
    height: 10,
    weight: 320,
    description: 'Always furious and tenacious to the bitter end.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png',
    hp: 65,
    attack: 105,
    defense: 60,
    spAtk: 60,
    spDef: 70,
    speed: 95
  },
  {
    id: 58,
    name: 'Growlithe',
    type: ['Fire'],
    height: 7,
    weight: 190,
    description: 'Extremely loyal, it will place itself in front of the trainer to protect them from attack.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png',
    hp: 55,
    attack: 70,
    defense: 45,
    spAtk: 70,
    spDef: 50,
    speed: 60
  },
  {
    id: 59,
    name: 'Arcanine',
    type: ['Fire'],
    height: 19,
    weight: 1550,
    description: 'A Pokémon that has been admired since the past. It runs agilely as if on wings.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png',
    hp: 90,
    attack: 110,
    defense: 80,
    spAtk: 100,
    spDef: 80,
    speed: 95
  },
  {
    id: 60,
    name: 'Poliwag',
    type: ['Water'],
    height: 6,
    weight: 124,
    description: 'Its newly grown legs can carry it only poorly. It appears to prefer swimming.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png',
    hp: 40,
    attack: 50,
    defense: 40,
    spAtk: 40,
    spDef: 40,
    speed: 90
  },
  {
    id: 61,
    name: 'Poliwhirl',
    type: ['Water'],
    height: 10,
    weight: 200,
    description: 'Capable of living both in water and on land. When in land, it sweats to keep its skin moist.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png',
    hp: 65,
    attack: 65,
    defense: 65,
    spAtk: 50,
    spDef: 50,
    speed: 90
  },
  {
    id: 62,
    name: 'Poliwrath',
    type: ['Water', 'Fighting'],
    height: 13,
    weight: 540,
    description: 'An master of moves that use water to damage opponents.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png',
    hp: 90,
    attack: 95,
    defense: 95,
    spAtk: 70,
    spDef: 90,
    speed: 70
  },
  {
    id: 63,
    name: 'Abra',
    type: ['Psychic'],
    height: 9,
    weight: 195,
    description: 'Teleports away when in danger. It uses psychic powers during battle.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png',
    hp: 25,
    attack: 20,
    defense: 15,
    spAtk: 105,
    spDef: 55,
    speed: 90
  },
  {
    id: 64,
    name: 'Kadabra',
    type: ['Psychic'],
    height: 13,
    weight: 565,
    description: 'It emits special alpha waves from its body that induce a neurotoxin to fight enemies.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png',
    hp: 40,
    attack: 35,
    defense: 30,
    spAtk: 120,
    spDef: 70,
    speed: 105
  },
  {
    id: 65,
    name: 'Alakazam',
    type: ['Psychic'],
    height: 15,
    weight: 480,
    description: 'Its IQ is said to be around 5,000. It is a master of psychic Pokémon.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png',
    hp: 55,
    attack: 50,
    defense: 45,
    spAtk: 135,
    spDef: 85,
    speed: 120
  },
  {
    id: 66,
    name: 'Machop',
    type: ['Fighting'],
    height: 8,
    weight: 195,
    description: 'Loves to build and make muscles stronger. It frequently lifts boulders.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png',
    hp: 70,
    attack: 80,
    defense: 50,
    spAtk: 35,
    spDef: 35,
    speed: 35
  },
  {
    id: 67,
    name: 'Machoke',
    type: ['Fighting'],
    height: 15,
    weight: 705,
    description: 'Its muscles never grow fatigued. It can always knock down any opponent.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png',
    hp: 80,
    attack: 100,
    defense: 70,
    spAtk: 50,
    spDef: 60,
    speed: 45
  },
  {
    id: 68,
    name: 'Machamp',
    type: ['Fighting'],
    height: 16,
    weight: 1300,
    description: 'With four arms, it can process four things at once.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png',
    hp: 90,
    attack: 130,
    defense: 80,
    spAtk: 65,
    spDef: 85,
    speed: 55
  },
  {
    id: 69,
    name: 'Bellsprout',
    type: ['Grass', 'Poison'],
    height: 7,
    weight: 40,
    description: 'A small Pokémon that lives in the shadows of tall trees in forests.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png',
    hp: 50,
    attack: 75,
    defense: 35,
    spAtk: 70,
    spDef: 30,
    speed: 40
  },
  {
    id: 70,
    name: 'Weepinbell',
    type: ['Grass', 'Poison'],
    height: 10,
    weight: 65,
    description: 'The fluid secreted by its flower petals is known to be sweet.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png',
    hp: 65,
    attack: 90,
    defense: 50,
    spAtk: 85,
    spDef: 50,
    speed: 55
  },
  {
    id: 71,
    name: 'Victreebel',
    type: ['Grass', 'Poison'],
    height: 17,
    weight: 155,
    description: 'Said to live in jungles of huge size. Eats and converts water and insects into energy.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png',
    hp: 80,
    attack: 105,
    defense: 65,
    spAtk: 100,
    spDef: 70,
    speed: 70
  },
  {
    id: 72,
    name: 'Tentacool',
    type: ['Water', 'Poison'],
    height: 9,
    weight: 450,
    description: 'Hides in sand on the seafloor. Is said to shoot any prey that stray into its area.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png',
    hp: 40,
    attack: 40,
    defense: 35,
    spAtk: 50,
    spDef: 100,
    speed: 70
  },
  {
    id: 73,
    name: 'Tentacruel',
    type: ['Water', 'Poison'],
    height: 16,
    weight: 550,
    description: 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png',
    hp: 80,
    attack: 70,
    defense: 65,
    spAtk: 80,
    spDef: 120,
    speed: 100
  },
  {
    id: 74,
    name: 'Geodude',
    type: ['Rock', 'Ground'],
    height: 4,
    weight: 200,
    description: 'Found in fields and mountains. It accumulates silt to make its body harder.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png',
    hp: 40,
    attack: 80,
    defense: 100,
    spAtk: 30,
    spDef: 30,
    speed: 20
  },
  {
    id: 75,
    name: 'Graveler',
    type: ['Rock', 'Ground'],
    height: 10,
    weight: 1050,
    description: 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing direction.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png',
    hp: 55,
    attack: 95,
    defense: 115,
    spAtk: 45,
    spDef: 45,
    speed: 35
  },
  {
    id: 76,
    name: 'Golem',
    type: ['Rock', 'Ground'],
    height: 14,
    weight: 3000,
    description: 'It is composed of four slabs of rock. It is solid all the way through and has no cavity.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png',
    hp: 80,
    attack: 120,
    defense: 130,
    spAtk: 55,
    spDef: 65,
    speed: 45
  },
  {
    id: 77,
    name: 'Ponyta',
    type: ['Fire'],
    height: 10,
    weight: 300,
    description: 'Its hooves are 10 times harder than diamond. It can withstand any type of attack.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png',
    hp: 50,
    attack: 85,
    defense: 55,
    spAtk: 65,
    spDef: 65,
    speed: 90
  },
  {
    id: 78,
    name: 'Rapidash',
    type: ['Fire', 'Ground'],
    height: 17,
    weight: 950,
    description: 'At full gallop, its four hooves barely touch the ground, creating a sound akin to a plane.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png',
    hp: 65,
    attack: 100,
    defense: 70,
    spAtk: 80,
    spDef: 80,
    speed: 105
  },
  {
    id: 79,
    name: 'Slowpoke',
    type: ['Water', 'Psychic'],
    height: 12,
    weight: 360,
    description: 'Incredibly slow and dopey. It takes 5 seconds for it to feel pain if it steps on a LEGO.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png',
    hp: 90,
    attack: 65,
    defense: 65,
    spAtk: 40,
    spDef: 40,
    speed: 15
  },
  {
    id: 80,
    name: 'Slowbro',
    type: ['Water', 'Psychic'],
    height: 16,
    weight: 785,
    description: 'Its tail has a Shellder firmly attached with a bite. As a result, the tail is not kept active.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png',
    hp: 95,
    attack: 75,
    defense: 110,
    spAtk: 100,
    spDef: 80,
    speed: 30
  },
  {
    id: 81,
    name: 'Seel',
    type: ['Water'],
    height: 11,
    weight: 900,
    description: 'Stores thermal energy in its body. A Coat of thick blubber keeps out cold.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png',
    hp: 65,
    attack: 45,
    defense: 55,
    spAtk: 45,
    spDef: 70,
    speed: 45
  },
  {
    id: 82,
    name: 'Dewgong',
    type: ['Water', 'Ice'],
    height: 17,
    weight: 1200,
    description: 'Stores thermal energy in its body. A Coat of thick blubber keeps out cold.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png',
    hp: 90,
    attack: 80,
    defense: 70,
    spAtk: 70,
    spDef: 95,
    speed: 70
  },
  {
    id: 83,
    name: 'Shellder',
    type: ['Water'],
    height: 3,
    weight: 40,
    description: 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png',
    hp: 30,
    attack: 65,
    defense: 100,
    spAtk: 45,
    spDef: 25,
    speed: 40
  },
  {
    id: 84,
    name: 'Cloyster',
    type: ['Water', 'Ice'],
    height: 15,
    weight: 1325,
    description: 'When attacked, it clamps down its shell, making it impossible to cause any damage.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png',
    hp: 50,
    attack: 95,
    defense: 180,
    spAtk: 85,
    spDef: 45,
    speed: 70
  },
  {
    id: 85,
    name: 'Gastly',
    type: ['Ghost', 'Poison'],
    height: 13,
    weight: 1,
    description: 'Said to emerge from darkness. Abhorred by many. It was long considered a myth until recently.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png',
    hp: 30,
    attack: 35,
    defense: 30,
    spAtk: 100,
    spDef: 35,
    speed: 80
  },
  {
    id: 86,
    name: 'Haunter',
    type: ['Ghost', 'Poison'],
    height: 16,
    weight: 1,
    description: 'It hides in shadows and is said to steal the lives of those who become lost in mountains.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png',
    hp: 45,
    attack: 50,
    defense: 45,
    spAtk: 115,
    spDef: 55,
    speed: 95
  },
  {
    id: 87,
    name: 'Gengar',
    type: ['Ghost', 'Poison'],
    height: 15,
    weight: 405,
    description: 'Its body temperature is said to drop nearly 10 degrees Fahrenheit in the presence of this Pokémon.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png',
    hp: 60,
    attack: 65,
    defense: 60,
    spAtk: 130,
    spDef: 75,
    speed: 110
  },
  {
    id: 88,
    name: 'Onix',
    type: ['Rock', 'Ground'],
    height: 87,
    weight: 2100,
    description: 'Made of rock. It is a solid creature. It sheds its skin once a year.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png',
    hp: 35,
    attack: 45,
    defense: 160,
    spAtk: 30,
    spDef: 45,
    speed: 70
  },
  {
    id: 89,
    name: 'Drowzee',
    type: ['Psychic'],
    height: 10,
    weight: 324,
    description: 'Puts enemies to sleep then eats their dreams.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png',
    hp: 60,
    attack: 48,
    defense: 45,
    spAtk: 43,
    spDef: 75,
    speed: 42
  },
  {
    id: 90,
    name: 'Hypno',
    type: ['Psychic'],
    height: 16,
    weight: 756,
    description: 'When it swings its pendulum, it mesmerizes its foe and puts it to sleep.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png',
    hp: 85,
    attack: 73,
    defense: 70,
    spAtk: 73,
    spDef: 115,
    speed: 67
  },
  {
    id: 91,
    name: 'Krabby',
    type: ['Water'],
    height: 4,
    weight: 65,
    description: 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png',
    hp: 30,
    attack: 105,
    defense: 90,
    spAtk: 25,
    spDef: 25,
    speed: 50
  },
  {
    id: 92,
    name: 'Kingler',
    type: ['Water'],
    height: 13,
    weight: 600,
    description: 'The large pincer is used for attack. It is powerful enough to break through rock.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png',
    hp: 55,
    attack: 130,
    defense: 115,
    spAtk: 50,
    spDef: 50,
    speed: 75
  },
  {
    id: 93,
    name: 'Voltorb',
    type: ['Electric'],
    height: 5,
    weight: 104,
    description: 'Usually found in power plants. Easily mistaken for a Poke Ball, can explode without warning.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png',
    hp: 40,
    attack: 30,
    defense: 50,
    spAtk: 55,
    spDef: 55,
    speed: 100
  },
  {
    id: 94,
    name: 'Electrode',
    type: ['Electric'],
    height: 12,
    weight: 666,
    description: 'It is said to move as fast as lightning and strike without ever being seen.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
    hp: 60,
    attack: 50,
    defense: 70,
    spAtk: 80,
    spDef: 80,
    speed: 150
  },
  {
    id: 95,
    name: 'Exeggcute',
    type: ['Grass', 'Psychic'],
    height: 4,
    weight: 25,
    description: 'Often seen in groups. It is said to communicate by moving its heads in a circle.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png',
    hp: 60,
    attack: 40,
    defense: 80,
    spAtk: 60,
    spDef: 45,
    speed: 40
  },
  {
    id: 96,
    name: 'Exeggutor',
    type: ['Grass', 'Psychic'],
    height: 20,
    weight: 1200,
    description: 'Its three heads think independently. It is occasionally seen screaming without regard to those around it.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png',
    hp: 95,
    attack: 95,
    defense: 85,
    spAtk: 125,
    spDef: 65,
    speed: 55
  },
  {
    id: 97,
    name: 'Cubone',
    type: ['Ground'],
    height: 4,
    weight: 65,
    description: 'Because it never removes its skull helmet, no one has ever seen this Pokémon\'s real face.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png',
    hp: 50,
    attack: 50,
    defense: 95,
    spAtk: 40,
    spDef: 50,
    speed: 35
  },
  {
    id: 98,
    name: 'Marowak',
    type: ['Ground'],
    height: 10,
    weight: 450,
    description: 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png',
    hp: 75,
    attack: 100,
    defense: 110,
    spAtk: 50,
    spDef: 80,
    speed: 45
  },
  {
    id: 99,
    name: 'Rhyhorn',
    type: ['Ground', 'Rock'],
    height: 10,
    weight: 1115,
    description: 'Its body\'s hide is extremely tough. It can withstand dynamite blasts without damage.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png',
    hp: 80,
    attack: 85,
    defense: 95,
    spAtk: 30,
    spDef: 30,
    speed: 25
  },
  {
    id: 100,
    name: 'Rhydon',
    type: ['Ground', 'Rock'],
    height: 19,
    weight: 1200,
    description: 'Its body\'s hide is extremely tough. It can withstand dynamite blasts without damage.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png',
    hp: 105,
    attack: 130,
    defense: 120,
    spAtk: 45,
    spDef: 45,
    speed: 40
  },
  {
    id: 101,
    name: 'Chansey',
    type: ['Normal'],
    height: 11,
    weight: 346,
    description: 'It is said to deliver eggs of happiness. It is considered a symbol of good fortune.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png',
    hp: 250,
    attack: 5,
    defense: 5,
    spAtk: 35,
    spDef: 105,
    speed: 30
  },
  {
    id: 102,
    name: 'Kangaskhan',
    type: ['Normal'],
    height: 22,
    weight: 800,
    description: 'The infant rarely ventures out of its mother\'s protective pouch until it is fully grown and self-reliant.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png',
    hp: 105,
    attack: 95,
    defense: 80,
    spAtk: 40,
    spDef: 80,
    speed: 90
  },
  {
    id: 103,
    name: 'Horsea',
    type: ['Water'],
    height: 4,
    weight: 80,
    description: 'Known to shoot down flying bugs with precision.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png',
    hp: 30,
    attack: 40,
    defense: 35,
    spAtk: 70,
    spDef: 25,
    speed: 60
  },
  {
    id: 104,
    name: 'Seadra',
    type: ['Water'],
    height: 12,
    weight: 250,
    description: 'Capable of swimming backwards. It propels itself by quickly flicking its tail fin.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png',
    hp: 55,
    attack: 65,
    defense: 95,
    spAtk: 95,
    spDef: 45,
    speed: 85
  },
  {
    id: 105,
    name: 'Goldeen',
    type: ['Water'],
    height: 15,
    weight: 150,
    description: 'Its tail fin undulates like an elegant ballroom dancer. It is a symbol of grace and beauty.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png',
    hp: 45,
    attack: 67,
    defense: 60,
    spAtk: 35,
    spDef: 50,
    speed: 63
  },
  {
    id: 106,
    name: 'Seaking',
    type: ['Water'],
    height: 13,
    weight: 390,
    description: 'In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png',
    hp: 80,
    attack: 92,
    defense: 65,
    spAtk: 65,
    spDef: 80,
    speed: 68
  },
  {
    id: 107,
    name: 'Staryu',
    type: ['Water'],
    height: 8,
    weight: 345,
    description: 'A strange gem is embedded in its center. Its body glows as it swims.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png',
    hp: 30,
    attack: 45,
    defense: 55,
    spAtk: 70,
    spDef: 55,
    speed: 85
  },
  {
    id: 108,
    name: 'Starmie',
    type: ['Water', 'Psychic'],
    height: 11,
    weight: 800,
    description: 'An enigmatic Pokémon that can cure any ailment. It is said to emerge from the sea.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png',
    hp: 60,
    attack: 75,
    defense: 85,
    spAtk: 100,
    spDef: 85,
    speed: 115
  },
  {
    id: 109,
    name: 'Mr. Mime',
    type: ['Psychic', 'Fairy'],
    height: 13,
    weight: 545,
    description: 'A master of pantomime. It can make anyone believe that something exists when it does not.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png',
    hp: 40,
    attack: 45,
    defense: 65,
    spAtk: 100,
    spDef: 120,
    speed: 90
  },
  {
    id: 110,
    name: 'Scyther',
    type: ['Bug', 'Flying'],
    height: 15,
    weight: 560,
    description: 'With wings that create high-pitched vibrations, it can fly at speeds exceeding 500 mph.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png',
    hp: 70,
    attack: 110,
    defense: 80,
    spAtk: 55,
    spDef: 80,
    speed: 105
  },
  {
    id: 111,
    name: 'Jynx',
    type: ['Ice', 'Psychic'],
    height: 14,
    weight: 406,
    description: 'It seduces its prey with a gurgling cry. It lives in icy regions.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png',
    hp: 65,
    attack: 50,
    defense: 35,
    spAtk: 115,
    spDef: 95,
    speed: 95
  },
  {
    id: 112,
    name: 'Electabuzz',
    type: ['Electric'],
    height: 11,
    weight: 300,
    description: 'Normally found near power plants. It can generate and store electricity.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png',
    hp: 65,
    attack: 83,
    defense: 57,
    spAtk: 95,
    spDef: 85,
    speed: 105
  },
  {
    id: 113,
    name: 'Magby',
    type: ['Fire'],
    height: 11,
    weight: 300,
    description: 'Normally found near power plants. It can generate and store fire.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png',
    hp: 65,
    attack: 95,
    defense: 57,
    spAtk: 100,
    spDef: 85,
    speed: 83
  },
  {
    id: 114,
    name: 'Lapras',
    type: ['Water', 'Ice'],
    height: 25,
    weight: 2160,
    description: 'A Pokémon that has been long considered a legend. It is said to travel the seas.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png',
    hp: 130,
    attack: 85,
    defense: 80,
    spAtk: 85,
    spDef: 95,
    speed: 60
  },
  {
    id: 115,
    name: 'Ditto',
    type: ['Normal'],
    height: 3,
    weight: 40,
    description: 'Capable of copying an enemy\'s genetic code to instantly transform itself into a duplicate of the enemy.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png',
    hp: 48,
    attack: 48,
    defense: 48,
    spAtk: 48,
    spDef: 48,
    speed: 48
  },
  {
    id: 116,
    name: 'Porygon',
    type: ['Normal'],
    height: 8,
    weight: 365,
    description: 'A Pokémon that consists entirely of programming code. It is capable of moving freely in cyberspace.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png',
    hp: 65,
    attack: 40,
    defense: 70,
    spAtk: 75,
    spDef: 100,
    speed: 40
  },
  {
    id: 117,
    name: 'Snorlax',
    type: ['Normal'],
    height: 21,
    weight: 4600,
    description: 'Very lazy. Just eats and sleeps. It is possible that it goes on a major eating spree.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png',
    hp: 150,
    attack: 80,
    defense: 50,
    spAtk: 40,
    spDef: 65,
    speed: 30
  },
  {
    id: 118,
    name: 'Articuno',
    type: ['Ice', 'Flying'],
    height: 17,
    weight: 554,
    description: 'A legendary bird Pokémon. It is said that its appearance is an omen of a long, harsh winter.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png',
    hp: 90,
    attack: 85,
    defense: 100,
    spAtk: 95,
    spDef: 125,
    speed: 85
  },
  {
    id: 119,
    name: 'Zapdos',
    type: ['Electric', 'Flying'],
    height: 16,
    weight: 526,
    description: 'A legendary bird Pokémon. It is said to live in thunderclouds.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png',
    hp: 90,
    attack: 90,
    defense: 85,
    spAtk: 125,
    spDef: 100,
    speed: 100
  },
  {
    id: 120,
    name: 'Moltres',
    type: ['Fire', 'Flying'],
    height: 20,
    weight: 499,
    description: 'A legendary bird Pokémon. It is said that this Pokémon emerged from the land to burn away all that was evil.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png',
    hp: 90,
    attack: 100,
    defense: 90,
    spAtk: 125,
    spDef: 85,
    speed: 100
  },
  {
    id: 121,
    name: 'Dratini',
    type: ['Dragon'],
    height: 18,
    weight: 33,
    description: 'Long considered a myth until recently when a small colony was discovered.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png',
    hp: 41,
    attack: 64,
    defense: 45,
    spAtk: 50,
    spDef: 50,
    speed: 50
  },
  {
    id: 122,
    name: 'Dragonair',
    type: ['Dragon'],
    height: 40,
    weight: 165,
    description: 'It is said that this Pokémon emerged from the land to destroy all that was evil.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png',
    hp: 61,
    attack: 84,
    defense: 65,
    spAtk: 70,
    spDef: 70,
    speed: 70
  },
  {
    id: 123,
    name: 'Dragonite',
    type: ['Dragon', 'Flying'],
    height: 22,
    weight: 2100,
    description: 'An extremely strong Pokémon that can level mountains with its power.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png',
    hp: 91,
    attack: 134,
    defense: 95,
    spAtk: 100,
    spDef: 100,
    speed: 80
  },
  {
    id: 124,
    name: 'Meowth',
    type: ['Psychic'],
    height: 8,
    weight: 400,
    description: 'Apparently, it was long considered a myth until recently when a small colony was discovered.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png',
    hp: 40,
    attack: 45,
    defense: 48,
    spAtk: 43,
    spDef: 72,
    speed: 42
  },
  {
    id: 125,
    name: 'Weezing',
    type: ['Poison'],
    height: 12,
    weight: 108,
    description: 'Where two kinds of poison gases meet, it is said that a new Pokémon is born.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png',
    hp: 65,
    attack: 90,
    defense: 120,
    spAtk: 85,
    spDef: 70,
    speed: 60
  },
  {
    id: 126,
    name: 'Rhyhorn',
    type: ['Rock', 'Ground'],
    height: 10,
    weight: 1115,
    description: 'Its horn is harder than diamond. A very powerful Pokémon.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png',
    hp: 80,
    attack: 85,
    defense: 95,
    spAtk: 30,
    spDef: 30,
    speed: 25
  },
  {
    id: 127,
    name: 'Chansey',
    type: ['Normal'],
    height: 11,
    weight: 346,
    description: 'It is said to deliver eggs of happiness. It is considered a symbol of good fortune.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png',
    hp: 250,
    attack: 5,
    defense: 5,
    spAtk: 35,
    spDef: 105,
    speed: 30
  },
  {
    id: 128,
    name: 'Kangaskhan',
    type: ['Normal'],
    height: 22,
    weight: 800,
    description: 'The infant rarely ventures out of its mother\'s protective pouch until it is fully grown.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png',
    hp: 105,
    attack: 95,
    defense: 80,
    spAtk: 40,
    spDef: 80,
    speed: 90
  },
  {
    id: 129,
    name: 'Horsea',
    type: ['Water'],
    height: 4,
    weight: 80,
    description: 'Known to shoot down flying bugs with precision.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png',
    hp: 30,
    attack: 40,
    defense: 35,
    spAtk: 70,
    spDef: 25,
    speed: 60
  },
  {
    id: 130,
    name: 'Seadra',
    type: ['Water'],
    height: 12,
    weight: 250,
    description: 'Capable of swimming backwards. It propels itself by quickly flicking its tail fin.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png',
    hp: 55,
    attack: 65,
    defense: 95,
    spAtk: 95,
    spDef: 45,
    speed: 85
  },
  {
    id: 131,
    name: 'Goldeen',
    type: ['Water'],
    height: 15,
    weight: 150,
    description: 'Its tail fin undulates like an elegant ballroom dancer.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png',
    hp: 45,
    attack: 67,
    defense: 60,
    spAtk: 35,
    spDef: 50,
    speed: 63
  },
  {
    id: 132,
    name: 'Seaking',
    type: ['Water'],
    height: 13,
    weight: 390,
    description: 'In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png',
    hp: 80,
    attack: 92,
    defense: 65,
    spAtk: 65,
    spDef: 80,
    speed: 68
  },
  {
    id: 133,
    name: 'Staryu',
    type: ['Water'],
    height: 8,
    weight: 345,
    description: 'A strange gem is embedded in its center. Its body glows as it swims.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png',
    hp: 30,
    attack: 45,
    defense: 55,
    spAtk: 70,
    spDef: 55,
    speed: 85
  },
  {
    id: 134,
    name: 'Starmie',
    type: ['Water', 'Psychic'],
    height: 11,
    weight: 800,
    description: 'An enigmatic Pokémon that can cure any ailment.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png',
    hp: 60,
    attack: 75,
    defense: 85,
    spAtk: 100,
    spDef: 85,
    speed: 115
  },
  {
    id: 135,
    name: 'Mr. Mime',
    type: ['Psychic', 'Fairy'],
    height: 13,
    weight: 545,
    description: 'A master of pantomime. It can make anyone believe that something exists.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png',
    hp: 40,
    attack: 45,
    defense: 65,
    spAtk: 100,
    spDef: 120,
    speed: 90
  },
  {
    id: 136,
    name: 'Scyther',
    type: ['Bug', 'Flying'],
    height: 15,
    weight: 560,
    description: 'With wings that create high-pitched vibrations, it can fly at high speeds.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png',
    hp: 70,
    attack: 110,
    defense: 80,
    spAtk: 55,
    spDef: 80,
    speed: 105
  },
  {
    id: 137,
    name: 'Jynx',
    type: ['Ice', 'Psychic'],
    height: 14,
    weight: 406,
    description: 'It seduces its prey with a gurgling cry.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png',
    hp: 65,
    attack: 50,
    defense: 35,
    spAtk: 115,
    spDef: 95,
    speed: 95
  },
  {
    id: 138,
    name: 'Electabuzz',
    type: ['Electric'],
    height: 11,
    weight: 300,
    description: 'Normally found near power plants. It can generate and store electricity.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png',
    hp: 65,
    attack: 83,
    defense: 57,
    spAtk: 95,
    spDef: 85,
    speed: 105
  },
  {
    id: 139,
    name: 'Magby',
    type: ['Fire'],
    height: 11,
    weight: 300,
    description: 'Normally found near power plants. It can generate and store fire.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png',
    hp: 65,
    attack: 95,
    defense: 57,
    spAtk: 100,
    spDef: 85,
    speed: 83
  },
  {
    id: 140,
    name: 'Lapras',
    type: ['Water', 'Ice'],
    height: 25,
    weight: 2160,
    description: 'A Pokémon that has been long considered a legend.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png',
    hp: 130,
    attack: 85,
    defense: 80,
    spAtk: 85,
    spDef: 95,
    speed: 60
  },
  {
    id: 141,
    name: 'Ditto',
    type: ['Normal'],
    height: 3,
    weight: 40,
    description: 'Capable of copying an enemy\'s genetic code to instantly transform itself.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png',
    hp: 48,
    attack: 48,
    defense: 48,
    spAtk: 48,
    spDef: 48,
    speed: 48
  },
  {
    id: 142,
    name: 'Porygon',
    type: ['Normal'],
    height: 8,
    weight: 365,
    description: 'A Pokémon that consists entirely of programming code.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png',
    hp: 65,
    attack: 40,
    defense: 70,
    spAtk: 75,
    spDef: 100,
    speed: 40
  },
  {
    id: 143,
    name: 'Snorlax',
    type: ['Normal'],
    height: 21,
    weight: 4600,
    description: 'Very lazy. Just eats and sleeps.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png',
    hp: 150,
    attack: 80,
    defense: 50,
    spAtk: 40,
    spDef: 65,
    speed: 30
  },
  {
    id: 144,
    name: 'Articuno',
    type: ['Ice', 'Flying'],
    height: 17,
    weight: 554,
    description: 'A legendary bird Pokémon. It is said that its appearance is an omen of a long, harsh winter.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png',
    hp: 90,
    attack: 85,
    defense: 100,
    spAtk: 95,
    spDef: 125,
    speed: 85
  },
  {
    id: 145,
    name: 'Zapdos',
    type: ['Electric', 'Flying'],
    height: 16,
    weight: 526,
    description: 'A legendary bird Pokémon. It is said to live in thunderclouds.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png',
    hp: 90,
    attack: 90,
    defense: 85,
    spAtk: 125,
    spDef: 100,
    speed: 100
  },
  {
    id: 146,
    name: 'Moltres',
    type: ['Fire', 'Flying'],
    height: 20,
    weight: 499,
    description: 'A legendary bird Pokémon. It is said that this Pokémon emerged from the land.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png',
    hp: 90,
    attack: 100,
    defense: 90,
    spAtk: 125,
    spDef: 85,
    speed: 100
  },
  {
    id: 147,
    name: 'Dratini',
    type: ['Dragon'],
    height: 18,
    weight: 33,
    description: 'Long considered a myth until recently when a small colony was discovered.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png',
    hp: 41,
    attack: 64,
    defense: 45,
    spAtk: 50,
    spDef: 50,
    speed: 50
  },
  {
    id: 148,
    name: 'Dragonair',
    type: ['Dragon'],
    height: 40,
    weight: 165,
    description: 'It is said that this Pokémon emerged from the land to destroy all that was evil.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png',
    hp: 61,
    attack: 84,
    defense: 65,
    spAtk: 70,
    spDef: 70,
    speed: 70
  },
  {
    id: 149,
    name: 'Dragonite',
    type: ['Dragon', 'Flying'],
    height: 22,
    weight: 2100,
    description: 'An extremely strong Pokémon that can level mountains with its power.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png',
    hp: 91,
    attack: 134,
    defense: 95,
    spAtk: 100,
    spDef: 100,
    speed: 80
  },
  {
    id: 150,
    name: 'Mewtwo',
    type: ['Psychic'],
    height: 20,
    weight: 1220,
    description: 'A legendary Pokémon that was created by a scientist after years of horrific gene splicing and DNA engineering.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
    hp: 106,
    attack: 110,
    defense: 90,
    spAtk: 154,
    spDef: 90,
    speed: 130
  },
  {
    id: 151,
    name: 'Mew',
    type: ['Psychic'],
    height: 4,
    weight: 40,
    description: 'Mew is said to be the ancestor of all Pokémon. It is larger than Mewtwo.',
    imageUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png',
    hp: 100,
    attack: 100,
    defense: 100,
    spAtk: 100,
    spDef: 100,
    speed: 100
  }
];

// Simple evolution chains for Generation 1 sample data
export const EVOLUTION_CHAINS: Record<number, number[]> = {
  1: [1,2,3],
  4: [4,5,6],
  7: [7,8,9],
  10: [10,11,12],
  13: [13,14,15],
  17: [17,18],
  25: [25,26]
};
